Revert "Merge branch 'master' into handle_retries_correctly"
This reverts commit 9ec882c6071bb0e199f1505f173be8e1daa98945, reversing
changes made to 91caaaf8483468eb39e4fc1e4cfd081e22ed0222.

payload.actionRequest.contact.emailAddress is not always populated and
can result in infinitely retrying because of a null pointer exception is
thrown with the log being

```
SpelEvaluationException: EL1007E: Property or field 'emailAddress' cannot be found on null
```